"""The core business logic: creating jobs, generating certificates, reading job state.

Routes (HTTP) call into here; nothing in this file knows about Flask requests.
"""
import logging
import uuid
from pathlib import Path

from .certificate import CertificateError, render_certificate
from .db import connect, now_iso
from .validation import validate_recipient

logger = logging.getLogger(__name__)

IN_PROGRESS = ("pending", "processing")


def _new_id():
    return uuid.uuid4().hex


def _text_or_none(value):
    """Store whatever the client sent for display in the failure list (never crash on junk)."""
    return value[:255] if isinstance(value, str) else None


# --------------------------------------------------------------------------- creating a job
def create_job(conn, job_fields, raw_recipients):
    """Insert the job and ONE row per recipient. Returns the new job id.

    Valid recipients start as 'pending' (to be generated by a worker).
    Invalid recipients are stored immediately as 'failed' with the reason, so the client
    can see exactly which input rows were rejected and why.
    """
    job_id = _new_id()
    now = now_iso()

    rows = []
    valid_count = 0
    for index, raw in enumerate(raw_recipients):
        clean, error = validate_recipient(raw)
        if error is None:
            valid_count += 1
            rows.append((_new_id(), job_id, index, clean["name"], clean["email"],
                         "pending", None, None, now, None))
        else:
            raw_dict = raw if isinstance(raw, dict) else {}
            rows.append((_new_id(), job_id, index, _text_or_none(raw_dict.get("name")),
                         _text_or_none(raw_dict.get("email")), "failed", None, error, now, now))

    # If nothing is valid there is nothing to process: the job is finished (failed) right away.
    status = "pending" if valid_count else "failed"
    conn.execute(
        "INSERT INTO jobs (id, status, title, event_name, issued_by, issue_date, total,"
        " created_at, completed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (job_id, status, job_fields["title"], job_fields["event_name"], job_fields["issued_by"],
         job_fields["issue_date"], len(rows), now, None if valid_count else now),
    )
    conn.executemany(
        "INSERT INTO certificates (id, job_id, row_index, recipient_name, recipient_email,"
        " status, file_path, error, created_at, completed_at) VALUES (?,?,?,?,?,?,?,?,?,?)",
        rows,
    )
    return job_id


# --------------------------------------------------------------------------- processing a job
def process_job(db_path, storage_dir, job_id, font_path=None):
    """Generate every pending certificate of a job. Runs in a background thread.

    Safe to call again for the same job: it only touches certificates still 'pending'
    (this is what makes crash-recovery work).
    """
    try:
        _process_job(db_path, storage_dir, job_id, font_path)
    except Exception as exc:  # last line of defence: never leave a job stuck in 'processing'
        logger.exception("Job %s crashed", job_id)
        with connect(db_path) as conn:
            conn.execute(
                "UPDATE jobs SET status = 'failed', error = ?, completed_at = ? WHERE id = ?",
                (f"Unexpected error: {exc}", now_iso(), job_id),
            )


def _process_job(db_path, storage_dir, job_id, font_path):
    with connect(db_path) as conn:
        job = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
        if job is None:
            return
        conn.execute(
            "UPDATE jobs SET status = 'processing', started_at = COALESCE(started_at, ?) WHERE id = ?",
            (now_iso(), job_id),
        )
        pending = conn.execute(
            "SELECT id, recipient_name FROM certificates"
            " WHERE job_id = ? AND status = 'pending' ORDER BY row_index",
            (job_id,),
        ).fetchall()

    # NOTE: no DB transaction is open while we render. Each certificate is saved on its own,
    # so progress is visible to status polling immediately and one failure can't undo others.
    for cert in pending:
        _generate_one(db_path, storage_dir, job, cert["id"], cert["recipient_name"], font_path)

    with connect(db_path) as conn:
        counts = _count_by_status(conn, job_id)
        if counts["failed"] == 0:
            final = "completed"
        elif counts["success"] == 0:
            final = "failed"
        else:
            final = "completed_with_errors"
        conn.execute("UPDATE jobs SET status = ?, completed_at = ? WHERE id = ?",
                     (final, now_iso(), job_id))


def _generate_one(db_path, storage_dir, job, cert_id, recipient_name, font_path):
    relative_path = f"{job['id']}/{cert_id}.pdf"
    output_path = Path(storage_dir) / relative_path
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        render_certificate(
            output_path,
            recipient_name=recipient_name,
            title=job["title"],
            event_name=job["event_name"],
            issued_by=job["issued_by"],
            issue_date=job["issue_date"],
            certificate_id=cert_id,
            font_path=font_path,
        )
        status, file_path, error = "success", relative_path, None
    except Exception as exc:  # ONE bad certificate must never stop the rest of the job
        if isinstance(exc, CertificateError):
            error = str(exc)
        else:
            logger.exception("Unexpected error generating certificate %s", cert_id)
            error = f"Unexpected error ({type(exc).__name__}): {exc}"
        status, file_path = "failed", None
        output_path.unlink(missing_ok=True)

    with connect(db_path) as conn:
        conn.execute(
            "UPDATE certificates SET status = ?, file_path = ?, error = ?, completed_at = ?"
            " WHERE id = ?",
            (status, file_path, error, now_iso(), cert_id),
        )


def recover_unfinished_jobs(db_path):
    """Ids of jobs interrupted by a restart/crash (still 'pending' or 'processing')."""
    with connect(db_path) as conn:
        rows = conn.execute(
            "SELECT id FROM jobs WHERE status IN ('pending', 'processing') ORDER BY created_at"
        ).fetchall()
    return [row["id"] for row in rows]


# --------------------------------------------------------------------------- reading state
def _count_by_status(conn, job_id):
    counts = {"pending": 0, "success": 0, "failed": 0}
    for row in conn.execute(
        "SELECT status, COUNT(*) AS n FROM certificates WHERE job_id = ? GROUP BY status", (job_id,)
    ):
        counts[row["status"]] = row["n"]
    return counts


def get_job(conn, job_id):
    """Job summary as a dict, or None. Counts are computed from the certificate rows,
    so they can never drift out of sync with reality."""
    job = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
    if job is None:
        return None
    counts = _count_by_status(conn, job_id)
    processed = counts["success"] + counts["failed"]
    summary = {
        "id": job["id"],
        "status": job["status"],
        "title": job["title"],
        "event_name": job["event_name"],
        "issued_by": job["issued_by"],
        "issue_date": job["issue_date"],
        "total": job["total"],
        "succeeded": counts["success"],
        "failed": counts["failed"],
        "pending": counts["pending"],
        "progress_percent": round(100 * processed / job["total"]) if job["total"] else 100,
        "created_at": job["created_at"],
        "started_at": job["started_at"],
        "completed_at": job["completed_at"],
    }
    if job["error"]:
        summary["error"] = job["error"]
    return summary


def get_failures(conn, job_id):
    rows = conn.execute(
        "SELECT row_index, recipient_name, recipient_email, error FROM certificates"
        " WHERE job_id = ? AND status = 'failed' ORDER BY row_index", (job_id,)
    ).fetchall()
    return [dict(row) for row in rows]


def list_certificates(conn, job_id, status=None, limit=100, offset=0):
    query = ("SELECT id, row_index, recipient_name, recipient_email, status, error, completed_at"
             " FROM certificates WHERE job_id = ?")
    params = [job_id]
    if status:
        query += " AND status = ?"
        params.append(status)
    query += " ORDER BY row_index LIMIT ? OFFSET ?"
    params += [limit, offset]
    return [dict(row) for row in conn.execute(query, params)]


def count_certificates(conn, job_id, status=None):
    query = "SELECT COUNT(*) AS n FROM certificates WHERE job_id = ?"
    params = [job_id]
    if status:
        query += " AND status = ?"
        params.append(status)
    return conn.execute(query, params).fetchone()["n"]


def get_certificate(conn, cert_id):
    row = conn.execute(
        "SELECT id, job_id, row_index, recipient_name, recipient_email, status, file_path,"
        " error, completed_at FROM certificates WHERE id = ?", (cert_id,)
    ).fetchone()
    return dict(row) if row else None


def successful_certificates(conn, job_id):
    rows = conn.execute(
        "SELECT row_index, recipient_name, file_path FROM certificates"
        " WHERE job_id = ? AND status = 'success' ORDER BY row_index", (job_id,)
    ).fetchall()
    return [dict(row) for row in rows]
